spring:
#  main:
#    allow-bean-definition-overriding: true
  batch:
    job:
      enabled: false

  shell:
    interactive:
      enabled: true
    noninteractive:
      enabled: false

    command:
      version:
        enabled: false


  data:
    mongodb:
#      host: localhost
      port: 0
      database: library

#    для подключения к реальной монге
#    mongodb:
#      port: 27017
#      database: library
#      host: localhost
#      authentication-database: admin
#      username: mongoadmin
#      password: secret

  datasource:
    url: jdbc:h2:mem:testdb

    username: sa
    password:
    driverClassName: org.h2.Driver
    #initialization-mode: always
    schema: schema.sql
    #data: data.sql
  jpa:
    hibernate:
      ddl-auto: none

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2


mongock:
#  runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

