spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
      javax:
        persistence:
          validation:
            mode: none
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:/db/db.changelog-master.yaml


server:
  port: 8000

  error:
    include-exception: true
    include-stacktrace: always

management:
  endpoint:
    health:
      show-details: always
  info:
    build:
      enabled: true
  endpoints:
    web:
      exposure.include: health, info, prometheus, metrics
  metrics:
    export:
      prometheus:
        enabled: true
